version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "example-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dl8qage6sgr5"
s3_prefix = "example-hello"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"test\""
