version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "eu-west-2"
parameter_overrides = "AppName=\"test\""


[default.build.parameters]
container_env_var = ["Function1.GITHUB_TOKEN=TOKEN1", "Function2.GITHUB_TOKEN=TOKEN2"]
container_env_var_file = "env.json"
